spring:
  application:
    name: producer
  cloud:
    function:
      definition: sendRiderLocation
    stream:
      function:
        definition: sendRiderLocation
      bindings:
        sendRiderLocation-out-0:
          destination: rider-location
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092